### PR TITLE
Convert to cgen

### PR DESCRIPTION
**Pull request by AlecTroemel**
friendship-meme

- [x] body.h
- [x] shapes.h
- [x] spaces.h
- [x] type.h.. this one may be more involved...
- [x] main.c
- [x] Clean up macros to handle abstract types cleaner

### CODE REVIEW

**Comment by pepe** [comment]
I see some hard action. I am sorry but I spent my time with not curses. Yet you seem to get into cgen quite in force. Super. I am AFK till Sun yet I will check from time time.

**Comment by AlecTroemel** [comment]
this kind of depends on https://github.com/janet-lang/jpm/pull/61

**Comment by AlecTroemel** [comment]
Im thinking about switching to this `defj` syntax

```janet
(defj cpMomentForCircle (float moment)
   "Calculate the moment of inertia for a hollow circle, r1 and r2 are the inner and outer diameters in no particular order."
   [(float m) (float r1) (float r2) (cpVect offset)])
```

I like that this looks basically like a function definition. The tricky part would be converting the chipmunk camelCase name to lispy kebab case. There's probably a PEG incantation to do that :laughing:

**Comment by AlecTroemel** [comment]
update, camel case to kebab was an interesting problem! Came up with this

```janet
(def camelCasePeg
  (peg/compile ~{:low-word (* (% (<- (some (range "az" "09"))))
                              (to (range "AZ")))
                 :cap-word (% (* (<- (range "AZ"))
                                 (some (<- (range "az" "09")))))
                 :main (* :low-word (any :cap-word))}))

(defn camel-to-kebab [str]
  (string/join
   (->> str
        (peg/match camelCasePeg)
        (map string/ascii-lower))
   "-"))
```

**Comment by AlecTroemel** [comment]
im going to merge this, future improvements or tweaks can always come in as other PR's

**Pull request merged**
